#!/usr/bin/perl

# requires: swaks
# 	sudo apt install swaks

if ($#ARGV != 3) {

  print <<EOF;
usage: ./run-send <subject> <email> <attachfile> <textfile>
	NULL for <attachfile> if no file to be attached
EOF
  exit;
}

$subject = $ARGV[0];
$email = $ARGV[1];
$attach = $ARGV[2];
$text = $ARGV[3];

print "SENDING $email: $subject\n";

if ($attach =~ /NULL/) {
print "SENDING - NO attachment\n";
$str=("swaks  -s \"127.0.0.1\" -p \"25\" -f \"Association of Korean Neuroscientists \<info\@akneuro.org\>\" -t \"$email\" --header \"Subject: $subject\" --body $text");
} else {
$str=("swaks  -s \"127.0.0.1\" -p \"25\" -f \"Association of Korean Neuroscientists \<info\@akneuro.org\>\" -t \"$email\" --header \"Subject: $subject\" --body $text --attach $attach");
}

#print $str;
system($str);
